# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.cluster_member_config_key import ClusterMemberConfigKey
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Cluster(BaseModel):
    """
    Cluster
    """ # noqa: E501
    enabled: Optional[StrictBool] = Field(default=None, description="Whether clustering is enabled", json_schema_extra={"examples": [True]})
    member_config: Optional[List[ClusterMemberConfigKey]] = Field(default=None, description="List of member configuration keys (used during join)  API extension: clustering_join", json_schema_extra={"examples": [[]]})
    server_name: Optional[StrictStr] = Field(default=None, description="Name of the cluster member answering the request", json_schema_extra={"examples": ["server01"]})
    __properties: ClassVar[List[str]] = ["enabled", "member_config", "server_name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Cluster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in member_config (list)
        _items = []
        if self.member_config:
            for _item_member_config in self.member_config:
                _items.append(_item_member_config.to_dict() if _item_member_config is not None else None)
            _dict['member_config'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Cluster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "member_config": [ClusterMemberConfigKey.from_dict(_item) for _item in obj["member_config"]] if obj.get("member_config") is not None else None,
            "server_name": obj.get("server_name")
        })
        return _obj


