# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.image_alias import ImageAlias
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ImageExportPost(BaseModel):
    """
    ImageExportPost represents the fields required to export an image
    """ # noqa: E501
    aliases: Optional[List[ImageAlias]] = Field(default=None, description="List of aliases to set on the image")
    certificate: Optional[StrictStr] = Field(default=None, description="Remote server certificate", json_schema_extra={"examples": ["X509 PEM certificate"]})
    profiles: Optional[List[StrictStr]] = Field(default=None, description="List of profiles to use  API extension: image_copy_profile", json_schema_extra={"examples": [["default"]]})
    project: Optional[StrictStr] = Field(default=None, description="Project name  API extension: image_target_project", json_schema_extra={"examples": ["project1"]})
    secret: Optional[StrictStr] = Field(default=None, description="Image receive secret", json_schema_extra={"examples": ["RANDOM-STRING"]})
    target: Optional[StrictStr] = Field(default=None, description="Target server URL", json_schema_extra={"examples": ["https://1.2.3.4:8443"]})
    __properties: ClassVar[List[str]] = ["aliases", "certificate", "profiles", "project", "secret", "target"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImageExportPost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in aliases (list)
        _items = []
        if self.aliases:
            for _item_aliases in self.aliases:
                _items.append(_item_aliases.to_dict() if _item_aliases is not None else None)
            _dict['aliases'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImageExportPost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aliases": [ImageAlias.from_dict(_item) for _item in obj["aliases"]] if obj.get("aliases") is not None else None,
            "certificate": obj.get("certificate"),
            "profiles": obj.get("profiles"),
            "project": obj.get("project"),
            "secret": obj.get("secret"),
            "target": obj.get("target")
        })
        return _obj


