# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.backup_target import BackupTarget
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstanceBackupsPost(BaseModel):
    """
    InstanceBackupsPost
    """ # noqa: E501
    compression_algorithm: Optional[StrictStr] = Field(default=None, description="What compression algorithm to use  API extension: backup_compression_algorithm", json_schema_extra={"examples": ["gzip"]})
    expires_at: Optional[datetime] = Field(default=None, description="When the backup expires (gets auto-deleted)", json_schema_extra={"examples": ["2021-03-23T17:38:37.753398689-04:00"]})
    instance_only: Optional[StrictBool] = Field(default=None, description="Whether to ignore snapshots", json_schema_extra={"examples": [False]})
    name: Optional[StrictStr] = Field(default=None, description="Backup name", json_schema_extra={"examples": ["backup0"]})
    optimized_storage: Optional[StrictBool] = Field(default=None, description="Whether to use a pool-optimized binary format (instead of plain tarball)", json_schema_extra={"examples": [True]})
    root_only: Optional[StrictBool] = Field(default=None, description="Whether to ignore dependent volumes", json_schema_extra={"examples": [False]})
    target: Optional[BackupTarget] = None
    __properties: ClassVar[List[str]] = ["compression_algorithm", "expires_at", "instance_only", "name", "optimized_storage", "root_only", "target"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceBackupsPost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceBackupsPost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compression_algorithm": obj.get("compression_algorithm"),
            "expires_at": obj.get("expires_at"),
            "instance_only": obj.get("instance_only"),
            "name": obj.get("name"),
            "optimized_storage": obj.get("optimized_storage"),
            "root_only": obj.get("root_only"),
            "target": BackupTarget.from_dict(obj["target"]) if obj.get("target") is not None else None
        })
        return _obj


