# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.metadata_config_key import MetadataConfigKey
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MetadataConfigGroup(BaseModel):
    """
    MetadataConfigGroup represents a group of config keys
    """ # noqa: E501
    keys: Optional[List[Dict[str, MetadataConfigKey]]] = None
    __properties: ClassVar[List[str]] = ["keys"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetadataConfigGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in keys (list of dict)
        _items = []
        if self.keys:
            for _item_keys in self.keys:
                _items.append(
                     {_inner_key: _inner_value.to_dict() if _inner_value is not None else None for _inner_key, _inner_value in _item_keys.items()} if _item_keys is not None else None
                )
            _dict['keys'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetadataConfigGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "keys": [
                    {_inner_key: MetadataConfigKey.from_dict(_inner_value) for _inner_key, _inner_value in _item.items()} if _item is not None else None
                    for _item in obj["keys"]
                ] if obj.get("keys") is not None else None
        })
        return _obj


