# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.network_state_address import NetworkStateAddress
from pyincusd.models.network_state_bond import NetworkStateBond
from pyincusd.models.network_state_bridge import NetworkStateBridge
from pyincusd.models.network_state_counters import NetworkStateCounters
from pyincusd.models.network_state_ovn import NetworkStateOVN
from pyincusd.models.network_state_vlan import NetworkStateVLAN
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NetworkState(BaseModel):
    """
    NetworkState represents the network state
    """ # noqa: E501
    addresses: Optional[List[NetworkStateAddress]] = Field(default=None, description="List of addresses")
    bond: Optional[NetworkStateBond] = None
    bridge: Optional[NetworkStateBridge] = None
    counters: Optional[NetworkStateCounters] = None
    hwaddr: Optional[StrictStr] = Field(default=None, description="MAC address", json_schema_extra={"examples": ["10:66:6a:5a:83:57"]})
    mtu: Optional[StrictInt] = Field(default=None, description="MTU", json_schema_extra={"examples": [1500]})
    ovn: Optional[NetworkStateOVN] = None
    state: Optional[StrictStr] = Field(default=None, description="Link state", json_schema_extra={"examples": ["up"]})
    type: Optional[StrictStr] = Field(default=None, description="Interface type", json_schema_extra={"examples": ["broadcast"]})
    vlan: Optional[NetworkStateVLAN] = None
    __properties: ClassVar[List[str]] = ["addresses", "bond", "bridge", "counters", "hwaddr", "mtu", "ovn", "state", "type", "vlan"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in addresses (list)
        _items = []
        if self.addresses:
            for _item_addresses in self.addresses:
                _items.append(_item_addresses.to_dict() if _item_addresses is not None else None)
            _dict['addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of bond
        if self.bond:
            _dict['bond'] = self.bond.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bridge
        if self.bridge:
            _dict['bridge'] = self.bridge.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counters
        if self.counters:
            _dict['counters'] = self.counters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ovn
        if self.ovn:
            _dict['ovn'] = self.ovn.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vlan
        if self.vlan:
            _dict['vlan'] = self.vlan.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addresses": [NetworkStateAddress.from_dict(_item) for _item in obj["addresses"]] if obj.get("addresses") is not None else None,
            "bond": NetworkStateBond.from_dict(obj["bond"]) if obj.get("bond") is not None else None,
            "bridge": NetworkStateBridge.from_dict(obj["bridge"]) if obj.get("bridge") is not None else None,
            "counters": NetworkStateCounters.from_dict(obj["counters"]) if obj.get("counters") is not None else None,
            "hwaddr": obj.get("hwaddr"),
            "mtu": obj.get("mtu"),
            "ovn": NetworkStateOVN.from_dict(obj["ovn"]) if obj.get("ovn") is not None else None,
            "state": obj.get("state"),
            "type": obj.get("type"),
            "vlan": NetworkStateVLAN.from_dict(obj["vlan"]) if obj.get("vlan") is not None else None
        })
        return _obj


