# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NetworkStateOVN(BaseModel):
    """
    NetworkStateOVN represents OVN specific state
    """ # noqa: E501
    chassis: Optional[StrictStr] = Field(default=None, description="OVN network chassis name", json_schema_extra={"examples": ["server01"]})
    logical_router: Optional[StrictStr] = Field(default=None, description="OVN logical router name  API extension: network_state_ovn_lr", json_schema_extra={"examples": ["incus-net1-lr"]})
    logical_switch: Optional[StrictStr] = Field(default=None, description="OVN logical switch name  API extension: network_state_ovn_ls", json_schema_extra={"examples": ["incus-net1-ls-int"]})
    uplink_ipv4: Optional[StrictStr] = Field(default=None, description="OVN network uplink ipv4 address  API extension: network_ovn_state_addresses", json_schema_extra={"examples": ["10.0.0.1"]})
    uplink_ipv6: Optional[StrictStr] = Field(default=None, description="OVN network uplink ipv6 address  API extension: network_ovn_state_addresses", json_schema_extra={"examples": ["2001:0000:130F:0000:0000:09C0:876A:130B"]})
    __properties: ClassVar[List[str]] = ["chassis", "logical_router", "logical_switch", "uplink_ipv4", "uplink_ipv6"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkStateOVN from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkStateOVN from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chassis": obj.get("chassis"),
            "logical_router": obj.get("logical_router"),
            "logical_switch": obj.get("logical_switch"),
            "uplink_ipv4": obj.get("uplink_ipv4"),
            "uplink_ipv6": obj.get("uplink_ipv6")
        })
        return _obj


