# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NetworkForwardPort(BaseModel):
    """
    NetworkForwardPort represents a port specification in a network address forward
    """ # noqa: E501
    description: Optional[StrictStr] = Field(default=None, description="Description of the forward port", json_schema_extra={"examples": ["My web server forward"]})
    listen_port: Optional[StrictStr] = Field(default=None, description="ListenPort(s) to forward (comma delimited ranges)", json_schema_extra={"examples": ["80,81,8080-8090"]})
    protocol: Optional[StrictStr] = Field(default=None, description="Protocol for port forward (either tcp or udp)", json_schema_extra={"examples": ["tcp"]})
    snat: Optional[StrictBool] = Field(default=None, description="SNAT controls whether to apply a matching SNAT rule to new outgoing traffic from the target  API extension: network_forward_snat", json_schema_extra={"examples": [False]})
    target_address: Optional[StrictStr] = Field(default=None, description="TargetAddress to forward ListenPorts to", json_schema_extra={"examples": ["198.51.100.2"]})
    target_port: Optional[StrictStr] = Field(default=None, description="TargetPort(s) to forward ListenPorts to (allows for many-to-one)", json_schema_extra={"examples": ["80,81,8080-8090"]})
    __properties: ClassVar[List[str]] = ["description", "listen_port", "protocol", "snat", "target_address", "target_port"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkForwardPort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkForwardPort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "listen_port": obj.get("listen_port"),
            "protocol": obj.get("protocol"),
            "snat": obj.get("snat"),
            "target_address": obj.get("target_address"),
            "target_port": obj.get("target_port")
        })
        return _obj


