# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.network_load_balancer_state_backend_health import NetworkLoadBalancerStateBackendHealth
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NetworkLoadBalancerState(BaseModel):
    """
    NetworkLoadBalancerState is used for showing current state of a load balancer
    """ # noqa: E501
    backend_health: Optional[Dict[str, NetworkLoadBalancerStateBackendHealth]] = None
    __properties: ClassVar[List[str]] = ["backend_health"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkLoadBalancerState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in backend_health (dict)
        _field_dict = {}
        if self.backend_health:
            for _key_backend_health in self.backend_health:
                _field_dict[_key_backend_health] = self.backend_health[_key_backend_health].to_dict() if self.backend_health[_key_backend_health] is not None else None
            _dict['backend_health'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkLoadBalancerState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backend_health": dict(
                (_k, NetworkLoadBalancerStateBackendHealth.from_dict(_v))
                for _k, _v in obj["backend_health"].items()
            )
            if obj.get("backend_health") is not None
            else None
        })
        return _obj


