# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_gpu_card_drm import ResourcesGPUCardDRM
from pyincusd.models.resources_gpu_card_mdev import ResourcesGPUCardMdev
from pyincusd.models.resources_gpu_card_nvidia import ResourcesGPUCardNvidia
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesGPUCard(BaseModel):
    """
    ResourcesGPUCard represents a GPU card on the system
    """ # noqa: E501
    driver: Optional[StrictStr] = Field(default=None, description="Kernel driver currently associated with the GPU", json_schema_extra={"examples": ["i915"]})
    driver_version: Optional[StrictStr] = Field(default=None, description="Version of the kernel driver", json_schema_extra={"examples": ["5.8.0-36-generic"]})
    drm: Optional[ResourcesGPUCardDRM] = None
    mdev: Optional[Dict[str, ResourcesGPUCardMdev]] = Field(default=None, description="Map of available mediated device profiles  API extension: resources_gpu_mdev")
    numa_node: Optional[StrictInt] = Field(default=None, description="NUMA node the GPU is a part of", json_schema_extra={"examples": [0]})
    nvidia: Optional[ResourcesGPUCardNvidia] = None
    pci_address: Optional[StrictStr] = Field(default=None, description="PCI address", json_schema_extra={"examples": ["0000:00:02.0"]})
    product: Optional[StrictStr] = Field(default=None, description="Name of the product", json_schema_extra={"examples": ["HD Graphics 620"]})
    product_id: Optional[StrictStr] = Field(default=None, description="PCI ID of the product", json_schema_extra={"examples": ["5916"]})
    sriov: Optional[ResourcesGPUCardSRIOV] = None
    usb_address: Optional[StrictStr] = Field(default=None, description="USB address (for USB cards)  API extension: resources_gpu_usb", json_schema_extra={"examples": ["2:7"]})
    vendor: Optional[StrictStr] = Field(default=None, description="Name of the vendor", json_schema_extra={"examples": ["Intel Corporation"]})
    vendor_id: Optional[StrictStr] = Field(default=None, description="PCI ID of the vendor", json_schema_extra={"examples": ["8086"]})
    __properties: ClassVar[List[str]] = ["driver", "driver_version", "drm", "mdev", "numa_node", "nvidia", "pci_address", "product", "product_id", "sriov", "usb_address", "vendor", "vendor_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesGPUCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of drm
        if self.drm:
            _dict['drm'] = self.drm.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in mdev (dict)
        _field_dict = {}
        if self.mdev:
            for _key_mdev in self.mdev:
                _field_dict[_key_mdev] = self.mdev[_key_mdev].to_dict() if self.mdev[_key_mdev] is not None else None
            _dict['mdev'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of nvidia
        if self.nvidia:
            _dict['nvidia'] = self.nvidia.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sriov
        if self.sriov:
            _dict['sriov'] = self.sriov.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesGPUCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "driver": obj.get("driver"),
            "driver_version": obj.get("driver_version"),
            "drm": ResourcesGPUCardDRM.from_dict(obj["drm"]) if obj.get("drm") is not None else None,
            "mdev": dict(
                (_k, ResourcesGPUCardMdev.from_dict(_v))
                for _k, _v in obj["mdev"].items()
            )
            if obj.get("mdev") is not None
            else None,
            "numa_node": obj.get("numa_node"),
            "nvidia": ResourcesGPUCardNvidia.from_dict(obj["nvidia"]) if obj.get("nvidia") is not None else None,
            "pci_address": obj.get("pci_address"),
            "product": obj.get("product"),
            "product_id": obj.get("product_id"),
            "sriov": ResourcesGPUCardSRIOV.from_dict(obj["sriov"]) if obj.get("sriov") is not None else None,
            "usb_address": obj.get("usb_address"),
            "vendor": obj.get("vendor"),
            "vendor_id": obj.get("vendor_id")
        })
        return _obj

from pyincusd.models.resources_gpu_card_sriov import ResourcesGPUCardSRIOV
# TODO: Rewrite to not use raise_errors
ResourcesGPUCard.model_rebuild(raise_errors=False)

