# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_pcivpd import ResourcesPCIVPD
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesPCIDevice(BaseModel):
    """
    ResourcesPCIDevice represents a PCI device
    """ # noqa: E501
    driver: Optional[StrictStr] = Field(default=None, description="Kernel driver currently associated with the GPU", json_schema_extra={"examples": ["mgag200"]})
    driver_version: Optional[StrictStr] = Field(default=None, description="Version of the kernel driver", json_schema_extra={"examples": ["5.8.0-36-generic"]})
    iommu_group: Optional[StrictInt] = Field(default=None, description="IOMMU group number  API extension: resources_pci_iommu", json_schema_extra={"examples": [20]})
    numa_node: Optional[StrictInt] = Field(default=None, description="NUMA node the card is a part of", json_schema_extra={"examples": [0]})
    pci_address: Optional[StrictStr] = Field(default=None, description="PCI address", json_schema_extra={"examples": ["0000:07:03.0"]})
    product: Optional[StrictStr] = Field(default=None, description="Name of the product", json_schema_extra={"examples": ["MGA G200eW WPCM450"]})
    product_id: Optional[StrictStr] = Field(default=None, description="PCI ID of the product", json_schema_extra={"examples": ["0532"]})
    vendor: Optional[StrictStr] = Field(default=None, description="Name of the vendor", json_schema_extra={"examples": ["Matrox Electronics Systems Ltd"]})
    vendor_id: Optional[StrictStr] = Field(default=None, description="PCI ID of the vendor", json_schema_extra={"examples": ["102b"]})
    vpd: Optional[ResourcesPCIVPD] = None
    __properties: ClassVar[List[str]] = ["driver", "driver_version", "iommu_group", "numa_node", "pci_address", "product", "product_id", "vendor", "vendor_id", "vpd"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesPCIDevice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of vpd
        if self.vpd:
            _dict['vpd'] = self.vpd.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesPCIDevice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "driver": obj.get("driver"),
            "driver_version": obj.get("driver_version"),
            "iommu_group": obj.get("iommu_group"),
            "numa_node": obj.get("numa_node"),
            "pci_address": obj.get("pci_address"),
            "product": obj.get("product"),
            "product_id": obj.get("product_id"),
            "vendor": obj.get("vendor"),
            "vendor_id": obj.get("vendor_id"),
            "vpd": ResourcesPCIVPD.from_dict(obj["vpd"]) if obj.get("vpd") is not None else None
        })
        return _obj


