# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_memory_node import ResourcesMemoryNode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesMemory(BaseModel):
    """
    ResourcesMemory represents the memory resources available on the system
    """ # noqa: E501
    hugepages_size: Optional[StrictInt] = Field(default=None, description="Size of memory huge pages (bytes)", json_schema_extra={"examples": [2097152]})
    hugepages_total: Optional[StrictInt] = Field(default=None, description="Total of memory huge pages (bytes)", json_schema_extra={"examples": [429284917248]})
    hugepages_used: Optional[StrictInt] = Field(default=None, description="Used memory huge pages (bytes)", json_schema_extra={"examples": [429284917248]})
    nodes: Optional[List[ResourcesMemoryNode]] = Field(default=None, description="List of NUMA memory nodes  API extension: resources_v2")
    total: Optional[StrictInt] = Field(default=None, description="Total system memory (bytes)", json_schema_extra={"examples": [687194767360]})
    used: Optional[StrictInt] = Field(default=None, description="Used system memory (bytes)", json_schema_extra={"examples": [557450502144]})
    __properties: ClassVar[List[str]] = ["hugepages_size", "hugepages_total", "hugepages_used", "nodes", "total", "used"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesMemory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                _items.append(_item_nodes.to_dict() if _item_nodes is not None else None)
            _dict['nodes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesMemory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hugepages_size": obj.get("hugepages_size"),
            "hugepages_total": obj.get("hugepages_total"),
            "hugepages_used": obj.get("hugepages_used"),
            "nodes": [ResourcesMemoryNode.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "total": obj.get("total"),
            "used": obj.get("used")
        })
        return _obj


