# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_cpu_thread import ResourcesCPUThread
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesCPUCore(BaseModel):
    """
    ResourcesCPUCore represents a CPU core on the system
    """ # noqa: E501
    core: Optional[StrictInt] = Field(default=None, description="Core identifier within the socket", json_schema_extra={"examples": [0]})
    die: Optional[StrictInt] = Field(default=None, description="What die the CPU is a part of (for chiplet designs)  API extension: resources_cpu_core_die", json_schema_extra={"examples": [0]})
    flags: Optional[List[StrictStr]] = Field(default=None, description="List of CPU flags  API extension: resources_cpu_flags", json_schema_extra={"examples": [[]]})
    frequency: Optional[StrictInt] = Field(default=None, description="Current frequency", json_schema_extra={"examples": [3500]})
    threads: Optional[List[ResourcesCPUThread]] = Field(default=None, description="List of threads")
    __properties: ClassVar[List[str]] = ["core", "die", "flags", "frequency", "threads"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesCPUCore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in threads (list)
        _items = []
        if self.threads:
            for _item_threads in self.threads:
                if _item_threads:
                    _items.append(_item_threads.to_dict())
            _dict['threads'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesCPUCore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "core": obj.get("core"),
            "die": obj.get("die"),
            "flags": obj.get("flags"),
            "frequency": obj.get("frequency"),
            "threads": [ResourcesCPUThread.from_dict(_item) for _item in obj["threads"]] if obj.get("threads") is not None else None
        })
        return _obj


