# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StorageVolumeSnapshot(BaseModel):
    """
    StorageVolumeSnapshot represents a storage volume snapshot
    """ # noqa: E501
    config: Optional[Dict[str, Any]] = Field(default=None, description="ConfigMap type is used to hold incus config. In contrast to plain map[string]string it provides unmarshal methods for JSON and YAML, which gracefully handle numbers and bools.")
    content_type: Optional[StrictStr] = Field(default=None, description="The content type (filesystem or block)  API extension: custom_block_volumes", json_schema_extra={"examples": ["filesystem"]})
    created_at: Optional[datetime] = Field(default=None, description="Volume snapshot creation timestamp API extension: storage_volumes_created_at", json_schema_extra={"examples": ["2021-03-23T20:00:00-04:00"]})
    description: Optional[StrictStr] = Field(default=None, description="Description of the storage volume", json_schema_extra={"examples": ["My custom volume"]})
    expires_at: Optional[datetime] = Field(default=None, description="When the snapshot expires (gets auto-deleted)  API extension: custom_volume_snapshot_expiry", json_schema_extra={"examples": ["2021-03-23T17:38:37.753398689-04:00"]})
    name: Optional[StrictStr] = Field(default=None, description="Snapshot name", json_schema_extra={"examples": ["snap0"]})
    __properties: ClassVar[List[str]] = ["config", "content_type", "created_at", "description", "expires_at", "name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StorageVolumeSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StorageVolumeSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": obj.get("config"),
            "content_type": obj.get("content_type"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "expires_at": obj.get("expires_at"),
            "name": obj.get("name")
        })
        return _obj


