# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.storage_bucket_backup import StorageBucketBackup
from pyincusd.models.storage_bucket_key import StorageBucketKey
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StorageBucketFull(BaseModel):
    """
    StorageBucketFull
    """ # noqa: E501
    backups: Optional[List[StorageBucketBackup]] = Field(default=None, description="List of backups.")
    config: Optional[Dict[str, Any]] = Field(default=None, description="ConfigMap type is used to hold incus config. In contrast to plain map[string]string it provides unmarshal methods for JSON and YAML, which gracefully handle numbers and bools.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the storage bucket  API extension: storage_buckets", json_schema_extra={"examples": ["My custom bucket"]})
    keys: Optional[List[StorageBucketKey]] = Field(default=None, description="List of keys.")
    location: Optional[StrictStr] = Field(default=None, description="What cluster member this record was found on  API extension: storage_buckets", json_schema_extra={"examples": ["server01"]})
    name: Optional[StrictStr] = Field(default=None, description="Bucket name  API extension: storage_buckets", json_schema_extra={"examples": ["foo"]})
    project: Optional[StrictStr] = Field(default=None, description="Project name  API extension: storage_buckets_all_projects", json_schema_extra={"examples": ["project1"]})
    s3_url: Optional[StrictStr] = Field(default=None, description="Bucket S3 URL  API extension: storage_buckets", json_schema_extra={"examples": ["https://127.0.0.1:8080/foo"]})
    __properties: ClassVar[List[str]] = ["backups", "config", "description", "keys", "location", "name", "project", "s3_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StorageBucketFull from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in backups (list)
        _items = []
        if self.backups:
            for _item_backups in self.backups:
                if _item_backups:
                    _items.append(_item_backups.to_dict())
            _dict['backups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in keys (list)
        _items = []
        if self.keys:
            for _item_keys in self.keys:
                if _item_keys:
                    _items.append(_item_keys.to_dict())
            _dict['keys'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StorageBucketFull from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backups": [StorageBucketBackup.from_dict(_item) for _item in obj["backups"]] if obj.get("backups") is not None else None,
            "config": obj.get("config"),
            "description": obj.get("description"),
            "keys": [StorageBucketKey.from_dict(_item) for _item in obj["keys"]] if obj.get("keys") is not None else None,
            "location": obj.get("location"),
            "name": obj.get("name"),
            "project": obj.get("project"),
            "s3_url": obj.get("s3_url")
        })
        return _obj


