# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.storage_volume_post_target import StorageVolumePostTarget
from pyincusd.models.storage_volume_source import StorageVolumeSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StorageVolumePost(BaseModel):
    """
    StorageVolumePost represents the fields required to rename a storage pool volume
    """ # noqa: E501
    migration: Optional[StrictBool] = Field(default=None, description="Initiate volume migration  API extension: storage_api_remote_volume_handling", json_schema_extra={"examples": [False]})
    name: Optional[StrictStr] = Field(default=None, description="New volume name", json_schema_extra={"examples": ["foo"]})
    pool: Optional[StrictStr] = Field(default=None, description="New storage pool  API extension: storage_api_local_volume_handling", json_schema_extra={"examples": ["remote"]})
    project: Optional[StrictStr] = Field(default=None, description="New project name  API extension: storage_volume_project_move", json_schema_extra={"examples": ["foo"]})
    source: Optional[StorageVolumeSource] = None
    target: Optional[StorageVolumePostTarget] = None
    volume_only: Optional[StrictBool] = Field(default=None, description="Whether snapshots should be discarded (migration only)  API extension: storage_api_remote_volume_snapshots", json_schema_extra={"examples": [False]})
    __properties: ClassVar[List[str]] = ["migration", "name", "pool", "project", "source", "target", "volume_only"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StorageVolumePost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StorageVolumePost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "migration": obj.get("migration"),
            "name": obj.get("name"),
            "pool": obj.get("pool"),
            "project": obj.get("project"),
            "source": StorageVolumeSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "target": StorageVolumePostTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "volume_only": obj.get("volume_only")
        })
        return _obj


