# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.system_security_encrypted_volume import SystemSecurityEncryptedVolume
from pyincusd.models.system_security_secure_boot_certificate import SystemSecuritySecureBootCertificate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemSecurityState(BaseModel):
    """
    SystemSecurityState
    """ # noqa: E501
    drive_recovery_keys: Optional[Dict[str, StrictStr]] = None
    encrypted_volumes: Optional[List[SystemSecurityEncryptedVolume]] = None
    encryption_recovery_keys_retrieved: Optional[StrictBool] = None
    pool_recovery_keys: Optional[Dict[str, StrictStr]] = None
    secure_boot_certificates: Optional[List[SystemSecuritySecureBootCertificate]] = None
    secure_boot_enabled: Optional[StrictBool] = None
    system_state_is_trusted: Optional[StrictBool] = None
    system_state_status: Optional[StrictStr] = None
    tpm_public_key: Optional[StrictStr] = None
    tpm_status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["drive_recovery_keys", "encrypted_volumes", "encryption_recovery_keys_retrieved", "pool_recovery_keys", "secure_boot_certificates", "secure_boot_enabled", "system_state_is_trusted", "system_state_status", "tpm_public_key", "tpm_status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemSecurityState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in encrypted_volumes (list)
        _items = []
        if self.encrypted_volumes:
            for _item_encrypted_volumes in self.encrypted_volumes:
                _items.append(_item_encrypted_volumes.to_dict() if _item_encrypted_volumes is not None else None)
            _dict['encrypted_volumes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in secure_boot_certificates (list)
        _items = []
        if self.secure_boot_certificates:
            for _item_secure_boot_certificates in self.secure_boot_certificates:
                _items.append(_item_secure_boot_certificates.to_dict() if _item_secure_boot_certificates is not None else None)
            _dict['secure_boot_certificates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemSecurityState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "drive_recovery_keys": obj.get("drive_recovery_keys"),
            "encrypted_volumes": [SystemSecurityEncryptedVolume.from_dict(_item) for _item in obj["encrypted_volumes"]] if obj.get("encrypted_volumes") is not None else None,
            "encryption_recovery_keys_retrieved": obj.get("encryption_recovery_keys_retrieved"),
            "pool_recovery_keys": obj.get("pool_recovery_keys"),
            "secure_boot_certificates": [SystemSecuritySecureBootCertificate.from_dict(_item) for _item in obj["secure_boot_certificates"]] if obj.get("secure_boot_certificates") is not None else None,
            "secure_boot_enabled": obj.get("secure_boot_enabled"),
            "system_state_is_trusted": obj.get("system_state_is_trusted"),
            "system_state_status": obj.get("system_state_status"),
            "tpm_public_key": obj.get("tpm_public_key"),
            "tpm_status": obj.get("tpm_status")
        })
        return _obj


