# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.system_network_firewall_rule import SystemNetworkFirewallRule
from pyincusd.models.system_network_route import SystemNetworkRoute
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemNetworkVLAN(BaseModel):
    """
    SystemNetworkVLAN
    """ # noqa: E501
    addresses: Optional[List[StrictStr]] = None
    firewall_rules: Optional[List[SystemNetworkFirewallRule]] = None
    id: Optional[StrictInt] = None
    mtu: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    parent: Optional[StrictStr] = None
    required_for_online: Optional[StrictStr] = None
    roles: Optional[List[StrictStr]] = None
    routes: Optional[List[SystemNetworkRoute]] = None
    __properties: ClassVar[List[str]] = ["addresses", "firewall_rules", "id", "mtu", "name", "parent", "required_for_online", "roles", "routes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemNetworkVLAN from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in firewall_rules (list)
        _items = []
        if self.firewall_rules:
            for _item_firewall_rules in self.firewall_rules:
                _items.append(_item_firewall_rules.to_dict() if _item_firewall_rules is not None else None)
            _dict['firewall_rules'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in routes (list)
        _items = []
        if self.routes:
            for _item_routes in self.routes:
                _items.append(_item_routes.to_dict() if _item_routes is not None else None)
            _dict['routes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemNetworkVLAN from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addresses": obj.get("addresses"),
            "firewall_rules": [SystemNetworkFirewallRule.from_dict(_item) for _item in obj["firewall_rules"]] if obj.get("firewall_rules") is not None else None,
            "id": obj.get("id"),
            "mtu": obj.get("mtu"),
            "name": obj.get("name"),
            "parent": obj.get("parent"),
            "required_for_online": obj.get("required_for_online"),
            "roles": obj.get("roles"),
            "routes": [SystemNetworkRoute.from_dict(_item) for _item in obj["routes"]] if obj.get("routes") is not None else None
        })
        return _obj


