# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.system_network_interface_stats import SystemNetworkInterfaceStats
from pyincusd.models.system_network_lacp_state import SystemNetworkLACPState
from pyincusd.models.system_network_lldp_state import SystemNetworkLLDPState
from pyincusd.models.system_network_route import SystemNetworkRoute
from pyincusd.models.system_network_wireguard_state import SystemNetworkWireguardState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemNetworkInterfaceState(BaseModel):
    """
    SystemNetworkInterfaceState
    """ # noqa: E501
    addresses: Optional[List[StrictStr]] = None
    hwaddr: Optional[StrictStr] = None
    lacp: Optional[SystemNetworkLACPState] = None
    lldp: Optional[List[SystemNetworkLLDPState]] = None
    members: Optional[Dict[str, SystemNetworkInterfaceState]] = None
    mtu: Optional[StrictInt] = None
    roles: Optional[List[StrictStr]] = None
    routes: Optional[List[SystemNetworkRoute]] = None
    speed: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    stats: Optional[SystemNetworkInterfaceStats] = None
    type: Optional[StrictStr] = None
    wireguard: Optional[SystemNetworkWireguardState] = None
    __properties: ClassVar[List[str]] = ["addresses", "hwaddr", "lacp", "lldp", "members", "mtu", "roles", "routes", "speed", "state", "stats", "type", "wireguard"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemNetworkInterfaceState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of lacp
        if self.lacp:
            _dict['lacp'] = self.lacp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in lldp (list)
        _items = []
        if self.lldp:
            for _item_lldp in self.lldp:
                _items.append(_item_lldp.to_dict() if _item_lldp is not None else None)
            _dict['lldp'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in members (dict)
        _field_dict = {}
        if self.members:
            for _key_members in self.members:
                _field_dict[_key_members] = self.members[_key_members].to_dict() if self.members[_key_members] is not None else None
            _dict['members'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in routes (list)
        _items = []
        if self.routes:
            for _item_routes in self.routes:
                _items.append(_item_routes.to_dict() if _item_routes is not None else None)
            _dict['routes'] = _items
        # override the default output from pydantic by calling `to_dict()` of stats
        if self.stats:
            _dict['stats'] = self.stats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wireguard
        if self.wireguard:
            _dict['wireguard'] = self.wireguard.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemNetworkInterfaceState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addresses": obj.get("addresses"),
            "hwaddr": obj.get("hwaddr"),
            "lacp": SystemNetworkLACPState.from_dict(obj["lacp"]) if obj.get("lacp") is not None else None,
            "lldp": [SystemNetworkLLDPState.from_dict(_item) for _item in obj["lldp"]] if obj.get("lldp") is not None else None,
            "members": dict(
                (_k, SystemNetworkInterfaceState.from_dict(_v))
                for _k, _v in obj["members"].items()
            )
            if obj.get("members") is not None
            else None,
            "mtu": obj.get("mtu"),
            "roles": obj.get("roles"),
            "routes": [SystemNetworkRoute.from_dict(_item) for _item in obj["routes"]] if obj.get("routes") is not None else None,
            "speed": obj.get("speed"),
            "state": obj.get("state"),
            "stats": SystemNetworkInterfaceStats.from_dict(obj["stats"]) if obj.get("stats") is not None else None,
            "type": obj.get("type"),
            "wireguard": SystemNetworkWireguardState.from_dict(obj["wireguard"]) if obj.get("wireguard") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
SystemNetworkInterfaceState.model_rebuild(raise_errors=False)

