# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.system_storage_drive_smart import SystemStorageDriveSMART
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemStorageDrive(BaseModel):
    """
    SystemStorageDrive
    """ # noqa: E501
    boot: Optional[StrictBool] = None
    bus: Optional[StrictStr] = None
    capacity_in_bytes: Optional[StrictInt] = None
    encrypted: Optional[StrictBool] = None
    encrypted_id: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    member_pool: Optional[StrictStr] = None
    model_family: Optional[StrictStr] = None
    model_name: Optional[StrictStr] = None
    multipath: Optional[StrictBool] = None
    remote: Optional[StrictBool] = None
    removable: Optional[StrictBool] = None
    serial_number: Optional[StrictStr] = None
    smart: Optional[SystemStorageDriveSMART] = None
    wwn: Optional[StrictStr] = None
    wwn_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["boot", "bus", "capacity_in_bytes", "encrypted", "encrypted_id", "id", "member_pool", "model_family", "model_name", "multipath", "remote", "removable", "serial_number", "smart", "wwn", "wwn_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemStorageDrive from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of smart
        if self.smart:
            _dict['smart'] = self.smart.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemStorageDrive from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "boot": obj.get("boot"),
            "bus": obj.get("bus"),
            "capacity_in_bytes": obj.get("capacity_in_bytes"),
            "encrypted": obj.get("encrypted"),
            "encrypted_id": obj.get("encrypted_id"),
            "id": obj.get("id"),
            "member_pool": obj.get("member_pool"),
            "model_family": obj.get("model_family"),
            "model_name": obj.get("model_name"),
            "multipath": obj.get("multipath"),
            "remote": obj.get("remote"),
            "removable": obj.get("removable"),
            "serial_number": obj.get("serial_number"),
            "smart": SystemStorageDriveSMART.from_dict(obj["smart"]) if obj.get("smart") is not None else None,
            "wwn": obj.get("wwn"),
            "wwn_id": obj.get("wwn_id")
        })
        return _obj


