# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemStorageDriveSMART(BaseModel):
    """
    SystemStorageDriveSMART
    """ # noqa: E501
    available_spare: Optional[StrictInt] = None
    data_units_read: Optional[StrictInt] = None
    data_units_written: Optional[StrictInt] = None
    enabled: Optional[StrictBool] = None
    error: Optional[StrictStr] = None
    passed: Optional[StrictBool] = None
    percentage_used: Optional[StrictInt] = None
    power_on_hours: Optional[StrictInt] = None
    raw_read_error_rate: Optional[StrictInt] = None
    reallocated_sectors: Optional[StrictInt] = None
    seek_error_rate: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["available_spare", "data_units_read", "data_units_written", "enabled", "error", "passed", "percentage_used", "power_on_hours", "raw_read_error_rate", "reallocated_sectors", "seek_error_rate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemStorageDriveSMART from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemStorageDriveSMART from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "available_spare": obj.get("available_spare"),
            "data_units_read": obj.get("data_units_read"),
            "data_units_written": obj.get("data_units_written"),
            "enabled": obj.get("enabled"),
            "error": obj.get("error"),
            "passed": obj.get("passed"),
            "percentage_used": obj.get("percentage_used"),
            "power_on_hours": obj.get("power_on_hours"),
            "raw_read_error_rate": obj.get("raw_read_error_rate"),
            "reallocated_sectors": obj.get("reallocated_sectors"),
            "seek_error_rate": obj.get("seek_error_rate")
        })
        return _obj


