# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.system_network_bond import SystemNetworkBond
from pyincusd.models.system_network_dns import SystemNetworkDNS
from pyincusd.models.system_network_interface import SystemNetworkInterface
from pyincusd.models.system_network_proxy import SystemNetworkProxy
from pyincusd.models.system_network_time import SystemNetworkTime
from pyincusd.models.system_network_vlan import SystemNetworkVLAN
from pyincusd.models.system_network_wireguard import SystemNetworkWireguard
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemNetworkConfig(BaseModel):
    """
    SystemNetworkConfig
    """ # noqa: E501
    bonds: Optional[List[SystemNetworkBond]] = None
    confirmation_timeout: Optional[StrictStr] = Field(default=None, description="If defined, automatically roll back the new network changes after the specified timeout has elapsed unless those changes are confirmed before then.")
    dns: Optional[SystemNetworkDNS] = None
    interfaces: Optional[List[SystemNetworkInterface]] = None
    proxy: Optional[SystemNetworkProxy] = None
    time: Optional[SystemNetworkTime] = None
    vlans: Optional[List[SystemNetworkVLAN]] = None
    wireguard: Optional[List[SystemNetworkWireguard]] = None
    __properties: ClassVar[List[str]] = ["bonds", "confirmation_timeout", "dns", "interfaces", "proxy", "time", "vlans", "wireguard"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemNetworkConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bonds (list)
        _items = []
        if self.bonds:
            for _item_bonds in self.bonds:
                _items.append(_item_bonds.to_dict() if _item_bonds is not None else None)
            _dict['bonds'] = _items
        # override the default output from pydantic by calling `to_dict()` of dns
        if self.dns:
            _dict['dns'] = self.dns.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in interfaces (list)
        _items = []
        if self.interfaces:
            for _item_interfaces in self.interfaces:
                _items.append(_item_interfaces.to_dict() if _item_interfaces is not None else None)
            _dict['interfaces'] = _items
        # override the default output from pydantic by calling `to_dict()` of proxy
        if self.proxy:
            _dict['proxy'] = self.proxy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time
        if self.time:
            _dict['time'] = self.time.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in vlans (list)
        _items = []
        if self.vlans:
            for _item_vlans in self.vlans:
                _items.append(_item_vlans.to_dict() if _item_vlans is not None else None)
            _dict['vlans'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in wireguard (list)
        _items = []
        if self.wireguard:
            for _item_wireguard in self.wireguard:
                _items.append(_item_wireguard.to_dict() if _item_wireguard is not None else None)
            _dict['wireguard'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemNetworkConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bonds": [SystemNetworkBond.from_dict(_item) for _item in obj["bonds"]] if obj.get("bonds") is not None else None,
            "confirmation_timeout": obj.get("confirmation_timeout"),
            "dns": SystemNetworkDNS.from_dict(obj["dns"]) if obj.get("dns") is not None else None,
            "interfaces": [SystemNetworkInterface.from_dict(_item) for _item in obj["interfaces"]] if obj.get("interfaces") is not None else None,
            "proxy": SystemNetworkProxy.from_dict(obj["proxy"]) if obj.get("proxy") is not None else None,
            "time": SystemNetworkTime.from_dict(obj["time"]) if obj.get("time") is not None else None,
            "vlans": [SystemNetworkVLAN.from_dict(_item) for _item in obj["vlans"]] if obj.get("vlans") is not None else None,
            "wireguard": [SystemNetworkWireguard.from_dict(_item) for _item in obj["wireguard"]] if obj.get("wireguard") is not None else None
        })
        return _obj


