# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.system_storage_pool_scrub_status import SystemStoragePoolScrubStatus
from pyincusd.models.system_storage_pool_special import SystemStoragePoolSpecial
from pyincusd.models.system_storage_pool_trim_status import SystemStoragePoolTrimStatus
from pyincusd.models.system_storage_pool_volume import SystemStoragePoolVolume
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemStoragePool(BaseModel):
    """
    SystemStoragePool
    """ # noqa: E501
    alignment: Optional[StrictInt] = Field(default=None, description="Optionally, configure the sector alignment size for the pool; defaults to 4096 byte sectors. Must be a power of two. Can only be specified when initially creating the pool.")
    allow_mixed_dev_sizes: Optional[StrictBool] = Field(default=None, description="If true, allow creation of a pool with devices of different sizes.")
    cache: Optional[List[StrictStr]] = None
    cache_degraded: Optional[List[StrictStr]] = None
    devices: Optional[List[StrictStr]] = Field(default=None, description="Devices, Cache, Log, and Special can be modified to add/remove/replace devices in the pool.")
    devices_degraded: Optional[List[StrictStr]] = None
    encryption_key_status: Optional[StrictStr] = None
    last_scrub: Optional[SystemStoragePoolScrubStatus] = None
    last_trim: Optional[SystemStoragePoolTrimStatus] = None
    log: Optional[List[StrictStr]] = None
    log_degraded: Optional[List[StrictStr]] = None
    managed: Optional[StrictBool] = Field(default=None, description="Read-only fields returned from the server with additional pool information.")
    name: Optional[StrictStr] = Field(default=None, description="Name and Type cannot be changed after pool creation.")
    pool_allocated_space_in_bytes: Optional[StrictInt] = None
    raw_pool_size_in_bytes: Optional[StrictInt] = None
    special: Optional[SystemStoragePoolSpecial] = None
    special_degraded: Optional[List[StrictStr]] = None
    state: Optional[StrictStr] = None
    type: Optional[StrictStr] = Field(default=None, description="Supported pool types: zfs-raid0, zfs-raid1, zfs-raid10, zfs-raidz1, zfs-raidz2, zfs-raidz3.")
    usable_pool_size_in_bytes: Optional[StrictInt] = None
    volumes: Optional[List[SystemStoragePoolVolume]] = None
    __properties: ClassVar[List[str]] = ["alignment", "allow_mixed_dev_sizes", "cache", "cache_degraded", "devices", "devices_degraded", "encryption_key_status", "last_scrub", "last_trim", "log", "log_degraded", "managed", "name", "pool_allocated_space_in_bytes", "raw_pool_size_in_bytes", "special", "special_degraded", "state", "type", "usable_pool_size_in_bytes", "volumes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemStoragePool from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_scrub
        if self.last_scrub:
            _dict['last_scrub'] = self.last_scrub.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_trim
        if self.last_trim:
            _dict['last_trim'] = self.last_trim.to_dict()
        # override the default output from pydantic by calling `to_dict()` of special
        if self.special:
            _dict['special'] = self.special.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                _items.append(_item_volumes.to_dict() if _item_volumes is not None else None)
            _dict['volumes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemStoragePool from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alignment": obj.get("alignment"),
            "allow_mixed_dev_sizes": obj.get("allow_mixed_dev_sizes"),
            "cache": obj.get("cache"),
            "cache_degraded": obj.get("cache_degraded"),
            "devices": obj.get("devices"),
            "devices_degraded": obj.get("devices_degraded"),
            "encryption_key_status": obj.get("encryption_key_status"),
            "last_scrub": SystemStoragePoolScrubStatus.from_dict(obj["last_scrub"]) if obj.get("last_scrub") is not None else None,
            "last_trim": SystemStoragePoolTrimStatus.from_dict(obj["last_trim"]) if obj.get("last_trim") is not None else None,
            "log": obj.get("log"),
            "log_degraded": obj.get("log_degraded"),
            "managed": obj.get("managed"),
            "name": obj.get("name"),
            "pool_allocated_space_in_bytes": obj.get("pool_allocated_space_in_bytes"),
            "raw_pool_size_in_bytes": obj.get("raw_pool_size_in_bytes"),
            "special": SystemStoragePoolSpecial.from_dict(obj["special"]) if obj.get("special") is not None else None,
            "special_degraded": obj.get("special_degraded"),
            "state": obj.get("state"),
            "type": obj.get("type"),
            "usable_pool_size_in_bytes": obj.get("usable_pool_size_in_bytes"),
            "volumes": [SystemStoragePoolVolume.from_dict(_item) for _item in obj["volumes"]] if obj.get("volumes") is not None else None
        })
        return _obj


